### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- [x] Listen for 'keydown' events on the document.
- [x] rotate the car when the user presses an arrow key
