### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
- [x] Use absolute positioning for your image.
- [x] Listen to the document for space bar keydown events 
- [x] When user presses space, move your car every 16 milliseconds for a smooth movement.
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] remove unnecessary styling.
- [x] fix any bugs.
- [x] test functionality
