### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started.
- [x] update startCar function to update value of boolean.
- [x] update space bar listener so on every odd keydown, interval is cancelled & every even keydown interval is started
